name: SMACT CI

# CINTENT >> MANUAL_TRIGGER
# on: [push]
on: [repository_dispatch, workflow_dispatch]

jobs:
  # CINTENT >> NO_TRACEES
  # qa:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: pre-commit/action@v3.0.0

  test:
    # CINTENT >> CANT_RUN
    # needs: qa
    strategy:
      fail-fast: false
      matrix:
        # CINTENT >> REMOVE_MATRIX
        # python-version: ["3.8","3.9","3.10"]
        python-version: ["3.10"]

        # CINTENT >> UNSUPPORTED_OS
        # os: [ubuntu-latest,macos-latest,windows-latest]
        os: [ubuntu-latest]
    
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # CINTENT >> INSERT_CINTENT
    - uses: JavidDitty/setup-cintent@3638849e94bdb037f0a405375686a8550e6df904
      with:
        nonblocking: true

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt

    - name: Run tests
      run: python -m pytest -v

    # CINTENT >> INSERT_CINTENT
    - name: Upload CIntent Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ env.CINTENT_ARTIFACT_NAME }}
        path: ${{ env.CINTENT_LOGS }}
